/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import util.ConnectionFactory;
import java.sql.Connection;

public class Main {
   
    public static void main(String[] args) {
       
        System.out.println("hello");
        //Connection c = ConnectionFactory.getConnection();
        //ConnectionFactory.closeConnection(c);
       
    }
}
